---
# Cloudflare Dynamic DNS IP Updater
# cloudflare_ddns_updater_enabled: yes
# cloudflare_ddns_updater_config:
#   auth_email: ""           # The email used to login 'https://dash.cloudflare.com'
#   auth_method: "token"     # Set to "global" for Global API Key or "token" for Scoped API Token
#   auth_key: ""             # Your API Token or Global API Key
#   zone_identifier: ""      # Can be found in the "Overview" tab of your domain
#   record_name: ""          # Which record you want to be synced
#   ttl: "3600"              # Set the DNS TTL (seconds)
#   proxy: false             # Set the proxy to true or false
#   slacksitename: ""        # Title of site "Example Site"
#   slackchannel: ""         # Slack Channel #example
#   slackuri: ""             # URI for Slack WebHook "https://hooks.slack.com/services/xxxxx"

# DNS
# cloudflare_email: xxx  # The email used to login 'https://dash.cloudflare.com'
# cloudflare_api_token: xxx  # Your API Token or Global API Key
# cloudflare_dns_records:
#   - zone: example.com
#     type: CNAME
#     record: www
#     value: example.com
#     state: absent
