---
name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

categories:
  - title: '🚨 Breaking changes'
    labels:
      - breaking
  - title: '✨ Enhancements'
    labels:
      - enhancement
      - security
  - title: '🐛 Bug fixes'
    labels:
      - bug
      - refactor
  - title: '📚 Documentation'
    labels:
      - documentation

version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - enhancement
      - security
  patch:
    labels:
      - bug
      - refactor
      - documentation
      - deprecated
  default: patch

template: |
  ## What’s changed

  $CHANGES
