---
collections:
  - name: ansible.posix:0.1.0
  - name: community.general
  - name: kubernetes.core
  - name: devsec.hardening

roles:
  - name: cloudalchemy.node_exporter
  - name: geerlingguy.docker
  - name: geerlingguy.firewall
  - name: geerlingguy.kubernetes
  - name: geerlingguy.swap
  - name: oefenweb.postfix
  - name: rvm.ruby
  - name: stefangweichinger.ansible_rclone
