---
galaxy_info:
  role_name: proxmox
  author: vladgh
  description: Vlad's Proxmox Role
  license: Apache v2
  min_ansible_version: '2.11'
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - buster
dependencies: []
