---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  # must be able to `ssh molecule-test-instance`, edit your ~/.ssh/config
  - name: molecule-test-instance
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../prepare.yml
