---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include nfs role
      ansible.builtin.include_role:
        name: vladgh.system.nfs
      vars:
        skip_handlers: true
        nfs_exports:
          - '/home/public  *(rw,async,no_root_squash)'
