---
- name: Converge
  hosts: all
  become: yes
  roles:
    - ./roles/common
  vars:
    timezone: US/Central
    local_groups:
      - name: admins
        system: yes
        sudo: yes
    local_users:
      - name: test
        comment: Testing User
        groups: admins
        append: yes
        password: mypassword
        authorized_keys:
          - ssh-ed25519 AAAA testing
    additional_packages:
      - rolldice
    apt_extra_keys:
      url: https://download.docker.com/linux/ubuntu/gpg
      filename: docker
    apt_extra_repositories:
      - name: Add test Docker repository
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.docker.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    pip_install_packages: [pip-install-test]
    pip_user_install_packages:
      - user: test
        packages: [colorama]
        state: latest
    bash_extra_aliases:
      - alias: ll
        command: ls -lahpF
        dest: /root/.bashrc
        owner: root
        group: root
    cron_jobs:
      - name: Testing
        minute: '0'
        job: ls -lah > /dev/null
    mounts:
      - name: Test
        path: /mnt/boot
        src: /boot
        opts: bind
        fstype: none
    systemd_mounts:
      - name: SystemD Mount Test
        automount: no
        what: /srv
        where: /mnt/srv
        options: bind
        type: none
        service_state: started
        service_enabled: yes
      - name: SystemD Auto Mount Test
        automount: yes
        what: localhost:/media
        where: /mnt/media
        options: _netdev,auto
        type: nfs
        service_state: started
        service_enabled: yes
    install_ca_certificates: yes
    fail2ban_enabled: yes
    sysctl_overwrite:
      fs.inotify.max_user_watches: 524288
    unattended_upgrades_autoupdate_enabled: yes
    unattended_upgrades_autoupdate_reboot: "true"
    unattended_upgrades_autoupdate_mail_to: "root"
    unattended_upgrades_autoupdate_mail_on_error: yes
    shell_extra_commands:
      - name: Test
        cmd: touch test.txt
        chdir: /tmp
        creates: test.txt
