---
- name: Verify
  hosts: all
  become: yes

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - name: Don't do much here.
      debug:
        msg: "Not implemented at this time."
