---
- name: Install role dependencies
  ansible.builtin.apt:
    name:
      - gnupg2
      - apt-transport-https
    update_cache: yes
    state: present

- name: Add Hashicorp Apt signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Hashicorp repo configuration
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
  register: _hashicorp_repo

- name: Install Hashicorp Packer
  ansible.builtin.apt:
    name: packer
    state: present

- name: Install Hashicorp Terraform
  ansible.builtin.apt:
    name: terraform
    state: present

- name: Install Hashicorp Vault
  ansible.builtin.apt:
    name: vault
    state: present

# trigger tests
