---
- name: Converge
  hosts: all
  become: yes
  vars:
    local_users:
      - name: myuser
        shell: /sbin/nologin
    samba_netbios_name: NAS
    samba_server_string: NAS
    samba_workgroup: WORKGROUP
    samba_users:
      - name: 'myuser'
        password: 'mypass'
    samba_shares:
      - name: myshare
        path: '/opt/myshare'
        writable: 'yes'
        browseable: 'yes'
        valid_users: 'myuser'
        owner: 'myuser'
        group: 'myuser'
        create_mode: '0664'
        force_create_mode: '0664'
        directory_mode: '0775'
        force_directory_mode: '0775'
  roles:
    - ./roles/common
    - ./roles/samba
