---
- name: CloudFlare Dynamic DNS Updater
  ansible.builtin.import_tasks: ddns.yml
  when: cloudflare_ddns_updater_enabled is defined and cloudflare_ddns_updater_enabled|bool

- name: Provision DNS records
  ansible.builtin.import_tasks: dns-records.yml
  when: cloudflare_dns_records is defined and cloudflare_dns_records

- name: Override SystemD Resolve
  ansible.builtin.import_tasks: systemd.yml
  when: >
    ( dns_disable_stub_listener is defined and dns_disable_stub_listener | bool ) and
    ( ansible_distribution == 'Ubuntu' )
