---
- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Restart LoginD
  service:
    name: systemd-logind
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Update trusted CA certificates
  command: /usr/sbin/update-ca-certificates --fresh

- name: Restart SystemD mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.mount"
    state: "{{ item.service_state | default('started') }}"
    enabled: "{{ item.service_enabled | default('yes') }}"
    daemon_reload: yes
  with_items: "{{ systemd_mounts }}"
  when: ( item.automount is not defined ) or ( not item.automount )

- name: Restart SystemD auto mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.automount"
    state: "{{ item.service_state | default('started') }}"
    enabled: "{{ item.service_enabled | default('yes') }}"
    daemon_reload: yes
  with_items: "{{ systemd_mounts }}"
  when: item.automount is defined and item.automount
