---
galaxy_info:
  role_name: qemu_guest_agent
  author: vladgh
  description: Vlad's role for the QEMU Guest Agent
  license: Apache v2
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster

dependencies: []
