---
- name: Ensure GnuPG package is installed
  ansible.builtin.apt:
    name: gnupg2

- name: Add extra APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ ansible_distribution_release | default(omit) }}"
    filename: "{{ item.filename | default(omit) }}"
    update_cache: "{{ item.update_cache | default(false) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ apt_extra_repositories }}"

- name: Update Apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: _update_apt_cache
  until: _update_apt_cache is success
  retries: 3
  delay: 2

- name: Unattended upgrades
  block:
    - name: Install unattended upgrades package
      ansible.builtin.package:
        name: unattended-upgrades
        state: present
    - name: Copy unattended-upgrades configuration files in place
      ansible.builtin.template:
        src: "etc/apt/apt.conf.d/{{ item }}.j2"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - 10periodic
        - 50unattended-upgrades
