---
- name: Disable APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ ansible_distribution_release | default(omit) }}"
    filename: "{{ item.filename | default(omit) }}"
    update_cache: "{{ item.update_cache | default(true) }}"
    state: "{{ item.state | default('absent') }}"
  loop: "{{ apt_disable_repositories }}"
  when: apt_disable_repositories is defined and apt_disable_repositories

- name: Add extra APT repositories
  when: >
    ( apt_extra_keys is defined and apt_extra_keys ) or
    ( apt_extra_repositories is defined and apt_extra_repositories )
  block:
    - name: Ensure GnuPG package is installed
      ansible.builtin.apt:
        name: gnupg2
        update_cache: yes

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: "{{ item.id | default(omit) }}"
        url: "{{ item.url | default(omit) }}"
        keyring: "/etc/apt/trusted.gpg.d/{{ item.filename | default(item.id) }}.gpg"
      loop: "{{ apt_extra_keys }}"
      when: apt_extra_keys is defined and apt_extra_keys

    - name: Add extra APT repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        codename: "{{ ansible_distribution_release | default(omit) }}"
        filename: "{{ item.filename | default(omit) }}"
        update_cache: "{{ item.update_cache | default(true) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ apt_extra_repositories }}"
      when: apt_extra_repositories is defined and apt_extra_repositories
