---
- name: Ensure PipX is installed
  ansible.builtin.package:
    name: "{{ pip_package | default('pipx') }}"
    state: present

- name: Ensure PipX packages are installed
  become: true
  become_user: "{{ item.user | default(omit) }}"
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pipx') }}"
    install_deps: "{{ item.install_deps | default(false) }}"
  loop: "{{ pipx_packages | default([]) }}"
