---
- name: Run Shell Commands
  # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: "{{ item.cmd }}"
    chdir: "{{ item.chdir | default(omit) }}"
    creates: "{{ item.creates | default(omit) }}"
  loop: "{{ shell_extra_commands }}"
