---
- name: Change various sysctl-settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{ sysctl_overwrite }}"
  when: >
    ( sysctl_overwrite is defined and sysctl_overwrite ) and
    ansible_virtualization_type not in ['docker', 'lxc', 'openvz']
