---
- name: Unattended upgrades
  block:
    - name: Install unattended upgrades package
      ansible.builtin.package:
        name: unattended-upgrades
        state: present
    - name: Copy unattended-upgrades configuration files in place
      ansible.builtin.template:
        src: "etc/apt/apt.conf.d/{{ item }}.j2"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - 10periodic
        - 50unattended-upgrades
