---
#   Provision Ansible on node
# ansible-galaxy collection install vladgh.system
# ansible-playbook -u ubuntu --ask-pass --ask-become-pass vladgh.system.ansible --limit mynode
- name: Ansible
  hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
  - name: Update apt-get repo and cache
    ansible.builtin.apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 21600  # Update the apt cache if its older than 6 hours
  - name: Install required packages
    ansible.builtin.package:
      name: [sudo, python3]
      state: present
  - name: Ansible user
    ansible.builtin.user:
      name: ansible
      state: present
      uid: 2674
  - name: Ansible user authorized keys
    ansible.posix.authorized_key:
      user: ansible
      key: "{{ deploy_ssh_rsa }}"
      state: present
      exclusive: yes
  - name: Add Ansible user to Sudoers
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/00_ansible
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
