---
- name: Upgrade everything
  hosts: upgrade
  become: yes
  tasks:
    - name: Upgrade Debian Systems
      block:
        - name: Update apt-get repo and cache
          apt:
            update_cache: yes
            force_apt_get: yes
            cache_valid_time: 21600  # Update the apt cache if its older than 6 hours
        - name: Upgrade all apt packages
          apt:
            upgrade: dist
        - name: Remove dependencies that are no longer required
          apt:
            autoremove: yes
            purge: yes
        - name: Remove useless packages from the cache
          apt:
            autoclean: yes
        # - name: Check if a reboot is needed on all servers
        #   register: reboot_required_file
        #   stat:
        #     path: /var/run/reboot-required
        #     get_md5: no
        # - name: Reboot the box if kernel updated
        #   reboot:
        #     msg: "Reboot initiated by Ansible for kernel updates"
        #     connect_timeout: 5
        #     reboot_timeout: 300
        #     pre_reboot_delay: 0
        #     post_reboot_delay: 30
        #     test_command: uptime
        #   when: reboot_required_file.stat.exists and inventory_hostname != 'vdev'
      when: ansible_os_family is defined and ansible_os_family == 'Debian'

    - name: Unattended upgrades
      block:
        - name: Install unattended upgrades package
          ansible.builtin.package:
            name: unattended-upgrades
            state: present

        - name: Copy unattended-upgrades configuration files in place
          ansible.builtin.template:
            src: "etc/apt/apt.conf.d/{{ item }}.j2"
            dest: "/etc/apt/apt.conf.d/{{ item }}"
            owner: root
            group: root
            mode: 0644
          with_items:
            - 10periodic
            - 50unattended-upgrades
      when: unattended_upgrades_autoupdate_enabled is defined and unattended_upgrades_autoupdate_enabled|bool
