---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: instance
  #   groups:
  #     - ansible
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: molecule-ubuntu-focal-instance
    groups:
      - ansible
    image: ubuntu:focal
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: false
    env:
      ansible_user: ansible
      sudo_group: sudo
      deploy_group: deployer
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
