---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - ansible
    image: ${MOLECULE_DISTRO:-'ubuntu:focal'}
    dockerfile: ../Dockerfile.j2
    pre_build_image: false
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../prepare.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
