name: Labels

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
    branches:
      - main

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Label actions
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
