---
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  galaxy:
    name: Change Ansible Galaxy version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Change collection version to match tag
        run: |
          sed -Ei "s/^version: .*/version: ${{ env.RELEASE_VERSION }}/" galaxy.yml
      - name: Commit galaxy.yml
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "Update galaxy.yml for ${{ env.RELEASE_VERSION }}"
          file_pattern: galaxy.yml
  update_release_draft:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
