---
name: Release Drafter

on:
  workflow_dispatch:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Draft release
    runs-on: ubuntu-22.04
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
