---
- name: Converge
  hosts: all
  become: true
  vars:
    zsh_user: johnd
  pre_tasks:
    - name: "Add the user {{ zsh_user }}"
      ansible.builtin.user:
        name: "{{ zsh_user }}"
  tasks:
    - name: Include zsh role
      ansible.builtin.include_role:
        name: vladgh.system.zsh
